#**Week 2: Convolutional** **nets**

# Part I: Rescaling operations

In [1]:
import torch
import torch.nn as nn

## Exercise 1. Add padding manually!

(exercise in the slides, [7.3.1](http://d2l.ai/chapter_convolutional-neural-networks/padding-and-strides.html#padding))

In [39]:
# This is the original image
image = torch.tensor([[3,1,4,3],
                      [3,2,3,1],
                      [4,3,6,4],
                      [3,3,1,7]])

# Add some padding manually
padded_image = nn.functional.pad(image, (1,1,1,1))


In [41]:
padded_image

tensor([[0, 0, 0, 0, 0, 0],
        [0, 3, 1, 4, 3, 0],
        [0, 3, 2, 3, 1, 0],
        [0, 4, 3, 6, 4, 0],
        [0, 3, 3, 1, 7, 0],
        [0, 0, 0, 0, 0, 0]])

## Exercise 2: Explore padding and stride with `Conv2D`
### Ex. 2a: Explore padding

Declare a filter with kernel size 3 and zero padding using nn.conv2D().
- Apply it to the image *I* below
- Check the shape of the output

- Repeat the same, but now using padding 1. What are the dimentions of the output now?

- What will happen if padding is 2?

- Play with different sizes of kernels and padding.




In [42]:
I = torch.tensor([[3,1,4,3],
                  [3,2,3,1],
                  [4,3,6,4],
                  [3,3,1,7]], dtype=torch.float32).reshape((1,1,4,4))

nopadding = nn.Conv2d(1,1, kernel_size=3, bias=False, padding=0)
# inspect no padding
nopadding

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), bias=False)

Check the output shape

In [48]:
nopadding(I).shape

torch.Size([1, 1, 2, 2])

In [49]:
# Now repeat with padding 1
padding_one = nn.Conv2d(1,1, kernel_size=3, bias=False, padding=1)
padding_one(I).shape

torch.Size([1, 1, 4, 4])

In [50]:
# Now repeat with padding 1
padding_two = nn.Conv2d(1,1, kernel_size=3, bias=False, padding=2)
padding_two(I).shape

torch.Size([1, 1, 6, 6])

### Ex 2b: Explore stride with Conv2D

Using the filter of the previous exercise give stride various values, and inspect the resulting shapes




In [59]:
# declare a filter with 1 padding and 1 stride
# apply it and print the shape of the output

filter_p1_s1 = nn.Conv2d(1,1, kernel_size=3, bias=False, padding=1, stride=1)
print(filter_p1_s1(I).shape)

# declare the same filter with 1 padding and 2 stride
# apply it and print the shape of the output

filter_p1_s2 = nn.Conv2d(1,1, kernel_size=3, bias=False, padding=1, stride=2)
print(filter_p1_s2(I).shape)

# declare the same filter with 1 padding and (2,1) stride (uneven)
# apply it and print the shape of the output

filter_p1_s21 = nn.Conv2d(1,1, kernel_size=3, bias=False, padding=(2,1), stride=4)
print(filter_p1_s21(I).shape)

torch.Size([1, 1, 4, 4])
torch.Size([1, 1, 2, 2])
torch.Size([1, 1, 2, 1])


### Exercise 3: Pooling
Inspired from book example [7.5.1](http://d2l.ai/chapter_convolutional-neural-networks/pooling.html#padding-and-stride)

By default, the stride and the pooling window *have the same shape* in the PyTorch built-in class `nn.MaxPool2d`.  

For example, with `nn.MaxPool2d(2)`, we define a pooling window of shape (2, 2), so we get a stride shape of (2, 2) by default.

Of course, we can specify an arbitrary rectangular pooling window and specify the padding and stride for height and width, respectively. But this is not used commonly. As in `nn.MaxPool2d(3, padding=1, stride=2)`



In [62]:
# Lets create a sample tensor
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))

# First we apply a Max Pooling of size 2
fpool2d = nn.MaxPool2d(2)
print(fpool2d(X))
print(fpool2d(X).shape)

# Repeat similarily with average pooling
# the function is AvgPool2d
fpool2d = nn.MaxPool2d(3)
print(fpool2d(X))
print(fpool2d(X).shape)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])
torch.Size([1, 1, 2, 2])
tensor([[[[10.]]]])
torch.Size([1, 1, 1, 1])


Great! You made it!

Time to build your first convolutional network :)