#**Week 1 day 4: Introduction to image** **processing**

## Exercise 3:  Implement your own version of the cross-correlation operator

(exercise in the slides, book [7.2.1](http://d2l.ai/chapter_convolutional-neural-networks/conv-layer.html#the-cross-correlation-operation))

In [4]:
import numpy as np
import torch
import torch.nn as nn
import pandas as pd
import matplotlib.pyplot as plt
from skimage import data

In [25]:
# Fill in the gaps!
I = torch.IntTensor(range(1, 10, 1)).reshape(-1, 3)

W1 = torch.FloatTensor([0, 2, 3 , 4]).reshape(-1,2)


#W2 = torch.FloatTensor(256)

print("Input tensor I:\n", I)
print("\nConvolutional filter W1:\n", W1)
#print("\nConvolutional filter W2: \n", W2)

Input tensor I:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

Convolutional filter W1:
 tensor([[0., 2.],
        [3., 4.]])


In [28]:
np.empty((2,2))

array([[ 10.        , 190.22222222],
       [ 27.625     , 204.22222222]])

In [31]:
W1 * W1

tensor([[ 0.,  4.],
        [ 9., 16.]])

In [36]:
I[:2, :2]

tensor([[1, 2],
        [4, 5]], dtype=torch.int32)

In [38]:
W1.shape()

TypeError: 'torch.Size' object is not callable

In [64]:
I[0.0:2, 0:2]

TypeError: slice indices must be integers or None or have an __index__ method

In [61]:
W1

tensor([[0., 2.],
        [3., 4.]])

In [76]:
# Write your own function for cross-correlations
# function for cross-correlations
def corr2d(I,f):

    new_mat = np.empty((2,2))
    
    ih, iw = I.shape[0], I.shape[1]
    fh, fw = f.shape[0], f.shape[1]

    for h in range(new_mat.shape[0]):
        for w in range(new_mat.shape[1]):
            new_mat[h,w] = (I[h: h+fh, w:w+fw] * f).sum()
            
    
            
            
    
    return new_mat
corr2d(I,W1)
#print('W1:', corr2d(I,W1))
#print('W2 (ones):', corr2d(I,W2))

array([[36., 45.],
       [63., 72.]])

In [77]:
# Try out your function on the example image from MNIST
mnist_df = pd.read_csv("sample_data/mnist_train_small.csv", header=None)
mnist_image = torch.tensor(np.array(mnist_df.loc[1,1:])).resize_(28,28)

# Create figure with original, and result from filter W1 and W2
fig = plt.figure(figsize=(10, 10))

fig.add_subplot(1, 3, 1)
plt.imshow(mnist_image,cmap='gray')
plt.title("Original image")

fig.add_subplot(1, 3, 2)
plt.imshow(corr2d(mnist_image, W1),cmap='gray')
plt.title("W1 applied")

fig.add_subplot(1, 3, 3)
plt.imshow(corr2d(mnist_image, W2),cmap='gray')
plt.title("W2 applied")

plt.show()

FileNotFoundError: [Errno 2] No such file or directory: 'sample_data/mnist_train_small.csv'

### Exercise 3b: Convolutions in PyTorch
Now lets repeat the above exercise, using the built-in *Conv2d* class of Pytorch
- [nn.Conv2d](https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html) works the same as the corr2d function, except it expects a 4D tensor of dimensions: (batch, channel, height, width)
- As our data is currently a 2D tensor of dimensions (height, width), we need to add two dimensions of length 1 with the [torch.reshape()](https://pytorch.org/docs/stable/generated/torch.reshape.html) function.


In [ ]:
# Implement with `nn.Conv2d`
# Define the image and weights, as 4-d tensors
I = torch.tensor([[3,1,4,3],
                  [3,2,3,1],
                  [4,3,6,4],
                  [3,3,1,7]], dtype = torch.float).reshape(1,1,4,4)

# Same for W1 - note the alternative syntax
W1 = W1.float().reshape(1,1,3,3)


In [ ]:
# define the filter
k1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=(3,3), bias=False)
# assign weights. Note requires to use the Parameter class for proper initialization
# of the autograder. Not useful for this exercise but essential for deep learning :)
k1.weight = nn.Parameter(W1)
# apply to image I
k1(I)

**Exercise** Create the convolutional filter for W2, and apply it on I

In [ ]:
# Your code here

## Exercise 4: Experimenting with filters
The website below contains an interactive tool, where you try out different 3x3 convolutional filters. Experiment with them and try out different custom filters.

https://beej.us/blog/data/convolution-image-processing/

**Question 1**: Can you design a custom filter that highlights only vertical edges?

**Question 2**: Can you create a filter that rotates the entire image 90 degrees? Why or why not?

### Exercise 4b - implement filters with corr2d and Conv2d

Below some more filters are given, that you can apply to the example image from mnist.

In [ ]:
# Get convolution matrices from here:
# https://en.wikipedia.org/wiki/Kernel_(image_processing)
# https://beej.us/blog/data/convolution-image-processing/

edge = torch.tensor([[-1,-1,-1],
                     [-1, 8,-1],
                     [-1,-1,-1]])
sharpen = torch.tensor([[0 ,-1,0],
                        [-1, 16,-1],
                        [0,-1,0]])
emboss = torch.tensor([[-2, -1, 0],
                       [-1,  1, 1],
                       [ 0, 1, 2]])


# Create figure with original, and result from filter W1 and W2
fig = plt.figure(figsize=(10, 10))

fig.add_subplot(1, 4, 1)
plt.imshow(mnist_image,cmap='gray')
plt.title("Original image")

fig.add_subplot(1, 4, 2)
plt.imshow(corr2d(mnist_image, edge),cmap='gray')
plt.title("Edge applied")

fig.add_subplot(1, 4, 3)
plt.imshow(corr2d(mnist_image, sharpen),cmap='gray')
plt.title("Sharpen applied")

fig.add_subplot(1, 4, 4)
plt.imshow(corr2d(mnist_image, emboss),cmap='gray')
plt.title("Emboss applied")

plt.show()


**Exercise** Use the Conv2d class of pytorch to create an edge-detecting filter, and apply in on the MNIST sample image.

Remember to change the dimentions of the image to what Conv2d expects (Batch, Channels, Height, Width)

In [ ]:
# Fill in the gaps
# define the filter
filter = 
# assign weights. Note requires to use the Parameter class for proper initialization
# of the autograder. Not useful for this exercise but essential for deep learning :)
filter.weight = 


modified = filter(mnist_image.float().reshape(1,1,28,28))
print(modified[0,0].shape)
plt.imshow(modified[0].detach().permute(1,2,0), cmap='gray')


## Exercise 5: Cross correlation operator for multiple channels
(exercise in the slides, book [7.4.1](http://d2l.ai/chapter_convolutional-neural-networks/channels.html#multiple-input-channels))

Using Conv2d, implement the following cross-correlation computation with 2 input channels

![](http://d2l.ai/_images/conv-multi-in.svg)

In [ ]:
# Write the input tensor (both channels)
# What shape should it be?
# Recall that nn.Conv2d works with 4 dimentional tensors: batch, channel, height, width

input = torch.tensor(3,)

# write the kernel tensor (it has 2 filters, one per band)
kernel = 

# define the filter using Conv2d
f = nn.Conv2d

# assign the filter weights

# apply the filter on the input
f(input) 

Of course in our networks, we will not be assigning the kernel weights. We will learn them from data!

How? Check the following exercise!

## Exercise 6: Learn kernel weights from data!
Exercise in the slides, book [7.2.3](http://d2l.ai/chapter_convolutional-neural-networks/conv-layer.html#object-edge-detection-in-images), [7.2.4](http://d2l.ai/chapter_convolutional-neural-networks/conv-layer.html#learning-a-kernel)

**Data preparation**

First step: Construct an image as a tensor X, sized 6×8.

The middle four columns are black (0) and the rest are white (1).

In [ ]:
X = torch.ones((6, 8))
X[:, 2:6] = 0
print(X)
plt.imshow(X, cmap='gray')

Next, we construct a kernel K with a height of 1 and a width of 2. When we perform the cross-correlation operation with the input, if the horizontally adjacent elements are the same, the output is 0. Otherwise, the output is non-zero.

In [ ]:
K = torch.tensor([[1,-1]])

We are ready to perform the cross-correlation operation with arguments X (our input) and K (our kernel).

As you can see, we detect 1 for the edge from white to black and -1 for the edge from black to white. All other outputs take value 0.

In [ ]:
# use your own corr2d or the one from the d2l package
Y = corr2d(X, K)
print(Y)
plt.imshow(Y, cmap='gray')

**Learning a Kernel**

Designing an edge detector by finite differences `[1, -1]` is neat
if we know this is precisely what we are looking for.
However, as we look at larger kernels,
and consider successive layers of convolutions,
it might be impossible to specify
precisely what each filter should be doing manually.

Now let us see whether we can learn the kernel that generated `Y` from `X`
by looking at the input--output pairs only.

We first construct a convolutional layer
and initialize its kernel as a random tensor.
Next, in each iteration, we will use the squared error
to compare `Y` with the output of the convolutional layer.
We can then calculate the gradient to update the kernel.
For the sake of simplicity,
in the following
we use the built-in class
for two-dimensional convolutional layers
and ignore the bias.

In [ ]:
# Construct a two-dimensional convolutional layer with 1 output channel and a
# kernel of shape (1, 2). For the sake of simplicity, we ignore the bias here
conv2d = nn.Conv2d(1,1, kernel_size=(1, 2), bias=False)

# The two-dimensional convolutional layer uses four-dimensional input and
# output in the format of (batch, channel, height, width).
# In our case where the batch size (number of examples in the batch) and
# the number of channels are both 1
X = X.reshape((1, 1, 6, 8))
Y = Y.reshape((1, 1, 6, 7))

for i in range(10):
    Y_hat = conv2d(X)                 # Apply the kernel
    l = (Y_hat - Y) ** 2              # Calculate the loss
    conv2d.zero_grad()                # Set the existing gradients to zero
    l.sum().backward()                # Backpropagate the losses

    # Update the kernel weights with the new gradients
    conv2d.weight.data[:] -= 3e-2 * conv2d.weight.grad
    if (i + 1) % 2 == 0:
        print(f'batch {i + 1}, loss {l.sum():.3f}')

Note that the error has dropped to a small value after 10 iterations. Now we will take a look at the kernel tensor we learned.

In [ ]:
conv2d.weight.data.reshape((1, 2))

Indeed, the learned kernel tensor is remarkably close
to the kernel tensor `K` we defined earlier. Now let's apply it to our original data again.

In [ ]:
Y_hat = conv2d(X).detach()[0][0]

print(Y_hat)
plt.imshow(Y_hat, cmap='gray')

You've made it! That was the first convolutional filter you have learned from data!

**Exercise** If you have time: learn the edge detection filter using one MNIST image!

In [ ]:
X = mnist_image.float()/256
Y = corr2d(mnist_image, edge)

# Necessary reshapes for Conv2d
X = X.reshape((1, 1, 28, 28))
Y = Y.reshape((1, 1, 26, 26))

# Construct a two-dimensional convolutional layer with 1 output channel and a
# kernel of shape (3,3). For the sake of simplicity, we ignore the bias here
conv2d = 






In [ ]:
fig = plt.figure(figsize=(10, 10))

fig.add_subplot(1, 2, 1)
plt.imshow(conv2d(X).detach()[0][0], cmap='gray')
plt.title("Estimated image")

fig.add_subplot(1, 2, 2)
plt.imshow(Y[0][0], cmap='gray')
plt.title("Original image")
fig.show()

In [ ]:
fig = plt.figure(figsize=(10, 10))

fig.add_subplot(1, 2, 1)
plt.imshow(conv2d.weight.data[0][0])
plt.title("Estimated filter")

fig.add_subplot(1, 2, 2)
plt.imshow(edge)
plt.title("Original filter")
fig.show()

plt.imshow(edge)


In [ ]:
conv2d.weight.data[0][0]